services:
    stas-back:
        container_name: stas-back
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        command: sh -c "npm run start:prod"
        restart: always
        ports:
            - ${APP_PORT}:${APP_PORT}
        networks:
            - stas-net
        depends_on:
            - cf_mongo
            - cf_redis

networks:
    stas-net:
        driver: bridge
