services:
    stas-back:
        container_name: stas-back
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        command: sh -c "npm run start:prod"
        restart: always
        ports:
            - ${APP_PORT}:${APP_PORT}
